### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by ll-SKY-ll** [etkecc/synapse-admin#157]
https://github.com/etkecc/synapse-admin/blob/cb1314ab1dd2df564697a23982b6fec8226ae0ee/src/i18n/de.ts#L267

Current: _Damit dies funktioniert, muss der Raum mindestens einen lokalen Mitglied als Administrator haben._

Correct: _Damit dies funktioniert, muss der Raum mindestens ein lokales Mitglied als Administrator haben._

**Comment by aine-etke** [comment]
We don't have German-speaking developers, so it would be amazing if you could submit a PR with the correct translations for your native language!

We use automatic/machine translation for such cases, alas

**Comment by ll-SKY-ll** [comment]
alright :) will have a look at the rest of the code then :)

**Comment by aine-etke** [comment]
this one fixed in https://github.com/etkecc/synapse-admin/commit/abca842eb95145bfd2da0b5b58a19fd9c96b7c66, thank you!
