### ISSUE TITLE
Feature request [Purge remote media API]

### ISSUE THREAD

**Issue by ll-SKY-ll** [etkecc/synapse-admin#215]
Hey, what are your thoughts about adding the "Purge remote media API" functionality?

https://element-hq.github.io/synapse/latest/admin_api/media_admin_api.html#purge-remote-media-api

maybe with a little selector to purge all or something like a human readable date field since i would assume that most people cant naturally read unixtimestamps.

This api is often used after a HS admin is made aware that some nasty media has been sent to some rooms to remove those images from the local storage well before the (eventually) configured remote media retention kicks in

**Comment by aine-etke** [comment]
Sounds great!
It could be integrated as a toggle or dropdown into the existing [Delete media dialog](https://github.com/etkecc/synapse-admin/blob/main/src/components/media.tsx#L39)
