### ISSUE TITLE
Synapse-Admin tries to load well-knowns using https when logged into local server using http

### ISSUE THREAD

**Issue by Twi1ightSparkle** [etkecc/synapse-admin#238]
When using Synapse-Admin to manage a local Synapse, in my case on `http://localhost:8448`, when reloading the page when signed in, it tries to load well-knowns using https.

![screenshot_2024-12-16T10-14-04Z](https://github.com/user-attachments/assets/de2b5ffb-9ad7-4a78-9bc6-ce267e9b8502)

And the page doesn't render until this times out.

(I will file a separate issue shortly for the malformed User IDs)

Issue is not present upstream:

![screenshot_2024-12-16T10-12-55Z](https://github.com/user-attachments/assets/e0a5fbdb-0463-4656-9d11-221b6c28c72a)

**Comment by Twi1ightSparkle** [comment]
I don't need the well-knowns to work when running against local test Synapse instances*, but would be nice if I didn't have to wait for it to time out

> Requests with failed CORS usually fail immediately, aren't they?

It's not a CORS error, there is nothing listening for HTTPS on localhost:8448. Did a refresh and this time I got the proper error in Firefox. CORS error is a bit of a catch-all error unfortunately.
![image](https://github.com/user-attachments/assets/f0625f1d-8ffd-4823-8611-b7517dc54f77)


\* That said, if I am talking to Synapse on http, my well-knowns aren't gonna be encrypted either. And I'm probably not in a production environment without SSL on anything

**Comment by aine-etke** [comment]
that's fair, fixed
