### ISSUE TITLE
Malformed User IDs when the server name contains a colon

### ISSUE THREAD

**Issue by Twi1ightSparkle** [etkecc/synapse-admin#239]
I have not confirmed my suspicion by looking into the code, but I suspect Synapse-Admin gets confused when the server name includes a colon. In my case, the server name is `localhost:8448`. If I'm right about the reason, it will also break if the server name is an IPv6.

Both are legal server names: https://spec.matrix.org/v1.12/appendices/#server-name

When you click a user, it also tries to go to `https://admin.etke.cc/#/users/@localpart:localhost:8448:localhost:8448`.
The data returned from Synapse is correct.

![screenshot_2024-12-16T10-20-46Z](https://github.com/user-attachments/assets/716a4f7f-ad41-4105-83e2-05da4c56d2df)

Manually going to the correct URL for a user also doesn't work

![screenshot_2024-12-16T10-24-15Z](https://github.com/user-attachments/assets/4bd53a69-b43b-4c94-9c24-3587b848a00b)

The issue is not present upstream

![screenshot_2024-12-16T10-12-55Z](https://github.com/user-attachments/assets/4baca88a-b723-4a05-8b74-ebe8c2feaed3)

**Comment by aine-etke** [comment]
Thank you for noticing!
Fixed
