### ISSUE TITLE
"No rooms yet" message on Rooms tab

### ISSUE THREAD

**Issue by BohdanK-W32** [etkecc/synapse-admin#257]
I don't really know if the problem with my homeserver or the synapse-admin itself, but looks like the incompatibility with the latest admin API spec or something;

Admin API always return 0 rooms in "Rooms" and "Room directory".
However, everything is ok with the Users and User's media tabs.

I can access the room info when going to: Users ⇒ [some user] ⇒ Rooms ⇒ [some room] (with URL https://matrix-admin.example.com/#/rooms/![roomId]:example.com/show), only then I see the room info, members, etc., and can manipulate it, but cannot see the rooms list.

You can check the source code of my setup here: https://github.com/zapal-tech/matrix-stack

Homeserver version: Synapse 1.121

**Comment by aine-etke** [comment]
Do you actually have any _local_ rooms?

Please, provide API responses calling Admin API directly and using Synapse Admin (including request's params)

Synapse Admin is tested with latest available Synapse release, and there were no such issue noticed during the last test

**Comment by BohdanK-W32** [comment]
Yes, there are a lot of rooms, public and private types;
Request sent from Synapse Admin: GET https://matrix.example.com/_synapse/admin/v1/rooms?from=0&limit=50&order_by=name&dir=f

Response:
200

Body:
```json
{
  "offset": 0,
  "rooms": [],
  "total_rooms": 0
}
```

**Comment by BohdanK-W32** [comment]
However, when Synapse Admin sending the request: GET https://matrix.zapal.tech/_synapse/admin/v1/users/%40user.id%3Aexample.com/joined_rooms?from=0&limit=25&order_by=id&dir=b

The response looks like this:
200

Body:
```json
{
  "joined_rooms": [
    "!roomId:example.com",
     "... all the rooms user joined"
  ],
  "total": 16
}
```

**Comment by aine-etke** [comment]
Well, the API call is correct (you can verify it in Synapse Admin API docs), so why your Synapse instance doesn't return any rooms is a question to the running Synapse instance.

Unfortunately, from the perspective of a static js+CSS app that simply provides a human-readable view for the data returned by the server, everything is OK

**Comment by BohdanK-W32** [comment]
So that question related to Synapse itself and there is nothing to do with the homeserver API compatibility?

**Comment by aine-etke** [comment]
Yes, that's an odd behavior of the Synapse itself. There is no issue with Synapse Admin call of the Synapse Admin API.

As that's not a Synapse Admin issue, I'm closing this one
