### ISSUE TITLE
Regarding newly added "UI option to block deleted rooms from being rejoined" ON by default

### ISSUE THREAD

**Issue by krassle** [etkecc/synapse-admin#48]
As far as I understand it, this option #12 makes use of the [Delete Room API](https://element-hq.github.io/synapse/latest/admin_api/rooms.html#delete-room-api) in combination with the *off-by-default* `block` parameter, which states:
> - block - Optional. If set to true, this room will be added to a blocking list, preventing future attempts to join the room. Rooms can be blocked even if they're not yet known to the homeserver (only with [Version 1](https://element-hq.github.io/synapse/latest/admin_api/rooms.html#version-1-old-version) of the API). Defaults to false.

A common synapse-admin cleanup task is the need to purge empty (forgotten or faulty) rooms from the database. I often group rooms by members and delete forgotten rooms all in one go. But what I *do not* necessarily expect is to also put those rooms on a local **blocking list** effectively preventing my users from being able to (re-) join them ever again.

While this still *is* a very useful option (for old tomb-stoned rooms, or rooms with content violation) I think this *should not* be the default choice. It should default to OFF, and display a clarification stating that, by turning this ON - those rooms will be added to a local block list  effectively preventing users from (re-)joining them in the future and that this action is not going to be *easily* reversible as synapse-admin does not (yet) have an option to query and revert blocked rooms.

Thanks!

**Comment by aine-etke** [comment]
Thanks for the context!
Indeed, blocking by default doesn't seem right, fixed
