### ISSUE TITLE
Login with Token

### ISSUE THREAD

**Issue by daedric7** [etkecc/synapse-admin#55]
With serveral servers migrating to Native OIDC / MAS, Synapse-Admin doesn't work as it's unable to generate the required token.

One alternative would be to generate the token ourselves (via mas-cli) and then pass this token to Synapse-Admin.

Would this be possible ?

**Comment by jacotec** [comment]
I'm still trying to find out how this works. There is a new tab "Access token" but I can't find a reference how to gerenate one in MAS-CLI.

Shouldn't the access token creation finally work simply if I do a normal SSO login which is (already yet) delegated to MAS?

**Comment by aine-etke** [comment]
Synapse-Admin doesn't interact with MAS specifically, nor it MAS-aware. The new "login with token" option simply allows you to use existing access token, e.g. by generating it using mas-cli. So, consider it a "user-friendly workaround" until the https://github.com/etkecc/synapse-admin/issues/38 is done. How to generate such token with MAS is mentioned in the upstream's issue https://github.com/Awesome-Technologies/synapse-admin/issues/429:

```
mas-cli manage issue-compatibility-token --yes-i-want-to-grant-synapse-admin-privileges [username]
```

Please note that we at etke.cc do not use MAS currently.

**Comment by jacotec** [comment]
@aine-etke Thanks, Quentin gave me that command in the Matrix Auth room 5 minutes ago. Unfortunately still not working running MAS. I'm still getting the "You're not an admin" message when using the access token.

**Comment by sandhose** [comment]
It looks like the two buttons 'Sign in' and 'Sign in with SSO' are still tied up to the login flow discovery, meaning that if the server only advertises `m.login.sso`, the Sign in button will be greyed out, so submitting the access token won't work

**Comment by jacotec** [comment]
Thanks for the comment, sandhose!

@aine-etke Can you fix the grayed out button? ;-)

**Comment by aine-etke** [comment]
> @aine-etke Thanks, Quentin gave me that command in the Matrix Auth room 5 minutes ago. Unfortunately still not working running MAS. I'm still getting the "You're not an admin" message when using the access token.

The error message is what Synapse returns when you send a request to an admin api endpoint, that means the token you generated belongs to a matrix user with no homeserver admin permissions




> It looks like the two buttons 'Sign in' and 'Sign in with SSO' are still tied up to the login flow discovery, meaning that if the server only advertises `m.login.sso`, the Sign in button will be greyed out, so submitting the access token won't work

Oh, that's a problem

@beastafk could you make "Sign in" button work on Access token tab regardless of the available login flows, please?

**Comment by aine-etke** [comment]
@jacotec @sandhose button fixed in `etke-21` release

**Comment by beastafk** [comment]
Improved in #61
