### ISSUE TITLE
Does not work as ansible component

### ISSUE THREAD

**Issue by VityaSchel** [etkecc/synapse-admin#82]
Hello! I installed matrix and synapse via ansible playbook (https://github.com/spantaleev/matrix-docker-ansible-deploy)

It works correctly both from browser and when I do curl with Host header.

However I can't get synapse-admin to work. I followed this guide https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-synapse-admin.md and after all steps I'm still getting `404 page not found` on my matrix.[domain]/synapse-admin/ (and without trailing slash too).

Here is what I did:

1. After installing synapse as usual I've decided to add this component
2. I added `matrix_synapse_admin_enabled: true` to my `inventory/host_vars/matrix.[domain]/vars.yml`
3. I also added `matrix_synapse_container_labels_public_client_synapse_admin_api_enabled: true` to my vars.yml
4. I have not adjusted admin url. I have not added `matrix_synapse_admin_hostname` or `matrix_synapse_admin_path_prefix`
5. I ran `ansible-playbook -i inventory/hosts setup.yml --tags=setup-all` (later I also tried `ansible-playbook -i inventory/hosts setup.yml --tags=install-all` and `just setup-all`

After that I get 404 page. Even when I'm doing `curl localhost:[port i'm using for matrix]/synapse-admin -H 'Host: matrix.[domain]'` I'm still getting 404 page

**Comment by VityaSchel** [comment]
Looks like it fixed eventually after many tries with combinations of `just setup-all` 🤷‍♂️ 
Sorry for bothering you

**Comment by aine-etke** [comment]
This is synapse-admin application/software repo, not synapse-admin ansible automation repo.

If you have any issues with playbook automation - please, create an issue in the playbook repo. This repository is intended for application/software-related things only.
